[package]
name = "point_pi"
version = "0.9.0"
authors = ["jake"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.4"
gpio-cdev = "0.2"